// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type TweetsId } from './Tweets';
import { type PollsId } from './Polls';
import { type UsersId } from './Users';

/** Identifier type for public.comments */
export type CommentsId = string & { __brand: 'CommentsId' };

/** Represents the table public.comments */
export default interface Comments {
  id: CommentsId;

  content: string;

  media_url: string[] | null;

  tweet_id: TweetsId;

  poll_id: PollsId;

  user_id: UsersId;

  reply_to_id: CommentsId;

  updated_at: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.comments */
export interface CommentsInitializer {
  id: CommentsId;

  content: string;

  media_url?: string[] | null;

  tweet_id: TweetsId;

  poll_id: PollsId;

  user_id: UsersId;

  reply_to_id: CommentsId;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.comments */
export interface CommentsMutator {
  id?: CommentsId;

  content?: string;

  media_url?: string[] | null;

  tweet_id?: TweetsId;

  poll_id?: PollsId;

  user_id?: UsersId;

  reply_to_id?: CommentsId;

  updated_at?: Date;

  created_at?: Date;
}
