// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.content_type */
enum ContentType {
  tweet = 'tweet',
  poll = 'poll',
};

export default ContentType;
