// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';

/** Identifier type for public.followers */
export type FollowersId = string & { __brand: 'FollowersId' };

/** Represents the table public.followers */
export default interface Followers {
  id: FollowersId;

  follower_id: UsersId;

  followee_id: UsersId;

  created_at: Date;
}

/** Represents the initializer for the table public.followers */
export interface FollowersInitializer {
  id: FollowersId;

  follower_id: UsersId;

  followee_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.followers */
export interface FollowersMutator {
  id?: FollowersId;

  follower_id?: UsersId;

  followee_id?: UsersId;

  created_at?: Date;
}
