// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.hash_tags */
export type HashTagsId = string & { __brand: 'HashTagsId' };

/** Represents the table public.hash_tags */
export default interface HashTags {
  id: HashTagsId;

  hashtag: string;

  created_at: Date;

  count: string | null;
}

/** Represents the initializer for the table public.hash_tags */
export interface HashTagsInitializer {
  id: HashTagsId;

  hashtag: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: 1 */
  count?: string | null;
}

/** Represents the mutator for the table public.hash_tags */
export interface HashTagsMutator {
  id?: HashTagsId;

  hashtag?: string;

  created_at?: Date;

  count?: string | null;
}
