// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';
import { type TweetsId } from './Tweets';

/** Identifier type for public.likes */
export type LikesId = string & { __brand: 'LikesId' };

/** Represents the table public.likes */
export default interface Likes {
  id: LikesId;

  user_id: UsersId;

  tweet_id: TweetsId;

  created_at: Date;
}

/** Represents the initializer for the table public.likes */
export interface LikesInitializer {
  id: LikesId;

  user_id: UsersId;

  tweet_id: TweetsId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.likes */
export interface LikesMutator {
  id?: LikesId;

  user_id?: UsersId;

  tweet_id?: TweetsId;

  created_at?: Date;
}
