// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.message_channels */
export type MessageChannelsId = string & { __brand: 'MessageChannelsId' };

/** Represents the table public.message_channels */
export default interface MessageChannels {
  id: MessageChannelsId;

  created_at: Date;

  updated_at: Date;

  users: string[] | null;
}

/** Represents the initializer for the table public.message_channels */
export interface MessageChannelsInitializer {
  id: MessageChannelsId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  users?: string[] | null;
}

/** Represents the mutator for the table public.message_channels */
export interface MessageChannelsMutator {
  id?: MessageChannelsId;

  created_at?: Date;

  updated_at?: Date;

  users?: string[] | null;
}
