// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as NotificationType } from './NotificationType';
import { type default as ContentType } from './ContentType';
import { type UsersId } from './Users';

/** Identifier type for public.notifications */
export type NotificationsId = string & { __brand: 'NotificationsId' };

/** Represents the table public.notifications */
export default interface Notifications {
  id: NotificationsId;

  notif_type: NotificationType;

  post_type: ContentType;

  content_id: string;

  message: string;

  user_id: UsersId;

  seen: boolean | null;

  created_at: Date;
}

/** Represents the initializer for the table public.notifications */
export interface NotificationsInitializer {
  id: NotificationsId;

  notif_type: NotificationType;

  post_type: ContentType;

  content_id: string;

  message: string;

  user_id: UsersId;

  /** Default value: false */
  seen?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.notifications */
export interface NotificationsMutator {
  id?: NotificationsId;

  notif_type?: NotificationType;

  post_type?: ContentType;

  content_id?: string;

  message?: string;

  user_id?: UsersId;

  seen?: boolean | null;

  created_at?: Date;
}
