// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.notification_type */
enum NotificationType {
  verified = 'verified',
  mentions = 'mentions',
};

export default NotificationType;
