// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  user_name: string;

  email: string;

  bio: string | null;

  first_name: string | null;

  last_name: string | null;

  country: string | null;

  dob: Date | null;

  following: number;

  followers: number;

  profile_picture: string | null;

  verified: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  id: UsersId;

  user_name: string;

  email: string;

  bio?: string | null;

  first_name?: string | null;

  last_name?: string | null;

  country?: string | null;

  dob?: Date | null;

  /** Default value: 0 */
  following?: number;

  /** Default value: 0 */
  followers?: number;

  profile_picture?: string | null;

  /** Default value: false */
  verified?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  user_name?: string;

  email?: string;

  bio?: string | null;

  first_name?: string | null;

  last_name?: string | null;

  country?: string | null;

  dob?: Date | null;

  following?: number;

  followers?: number;

  profile_picture?: string | null;

  verified?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
