// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.visibility */
enum Visibility {
  public = 'public',
  private = 'private',
};

export default Visibility;
